Sys.setlocale("LC_TIME", "C")
mydata<-read.table("household_power_consumption.txt", sep=";", dec=".", col.names=c('Date','Time','Global_active_power','Global_reactive_power','Voltage','Global_intensity','Sub_metering_1','Sub_metering_2','Sub_metering_3'), na.strings='?', skip=66636, nrows=2880)
DateTime<-paste(mydata$Date, mydata$Time, sep=' ')
DateTime<-strptime(DateTime, format="%d/%m/%Y %H:%M:%S")
png('plot3.png', width=480, height=480)
plot(DateTime, mydata$Sub_metering_1, type='n', xlab='', ylab='Energy sub metering')
lines(DateTime, mydata$Sub_metering_1, type='l', xlab='', ylab='Energy sub metering')
lines(DateTime, mydata$Sub_metering_2, col='red', type='l', xlab='', ylab='Energy sub metering')
lines(DateTime, mydata$Sub_metering_3, col='blue', type='l', xlab='', ylab='Energy sub metering')
legend("topright",c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'), col=c("black","red","blue"), lwd=c(1,1,1), cex=0.8)
dev.off()